Content:
    achlys:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
           
Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Achlys
        repo: https://github.com/aurora-multiphysics/achlys
        menu:
            Documentation: documentation.menu.md
            Examples: examples.menu.md
            Source code: source_code.menu.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
#    MooseDocs.extensions.acronym:
#        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.template:
        active: True
