name: BuildTest
on:
  push:
    branches:
       - master
  pull_request:
    branches:
       - master

name: Deploy Nightly
on:
  schedule:
    - cron: '0 18 * * 0' # run at 6 PM UTC every Sunday

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: BuildTestUbuntu
    env:
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}
      COVERALLS_TOKEN : ${{ secrets.COVERALLS_TOKEN }}
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v2
      # Now build in a container with all deps
      - name: PrintGithubContext
        run: echo $PRCOMMITSHA
      - name: DockerBuildTestPR
        if:  ${{ github.event.pull_request.head.sha != '' }}
        run: docker build -t ci-achlys-ubuntu --build-arg build_git_sha=$PRCOMMITSHA docker/achlys-ubuntu/ --build-arg test_coverage=true --build-arg coveralls_token=$COVERALLS_TOKEN --build-arg coveralls_branch=$GITHUB_HEAD_REF
      - name:  DockerBuildTestPush
        if:  ${{ github.event.pull_request.head.sha == '' }}
        run: docker build -t ci-achlys-ubuntu --build-arg build_git_sha=$GITHUB_SHA docker/achlys-ubuntu/ --build-arg test_coverage=true --build-arg coveralls_token=$COVERALLS_TOKEN --build-arg coveralls_branch=${GITHUB_REF##*/}
