name: DeployNightly
on:
  - schedule:
    - cron: '0 18 * * 0' # run at 6 PM UTC every Sunday
  
  - workflow_dispatch

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: WeeklyUbuntu

    env:
      PRCOMMITSHA : ${{ github.event.pull_request.head.sha }}
      COVERALLS_TOKEN : ${{ secrets.COVERALLS_TOKEN }}
    
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v3

      # Now build in a container with all deps
      - name: PrintGithubContext
        run: echo $PRCOMMITSHA

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sdixonukaea
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sdixonukaea/achlys-ubuntu

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/achlys-ubuntu/moose-latest
          build-args: 
            - build_git_sha=$PRCOMMITSHA
            - test_coverage=true
            - coveralls_token=$COVERALLS_TOKEN
            - coveralls_branch=${GITHUB_REF##*/}  

